agents:
  queue: <%- prodBuildkiteQueueName %>

steps:
  - label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test:ci'
      - yarn test:ci
      - echo '--- yarn lint'
      - yarn lint
    env:
      GET_GITHUB_TOKEN: please
    plugins:
      - &aws-sm
        seek-oss/aws-sm#v2.3.1:
          env:
            NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token
      - &private-npm
        seek-oss/private-npm#v1.2.0:
          env: NPM_READ_TOKEN
      - docker-compose#v3.9.0:
          run: app

  - label: 📦 Build & Package
    plugins:
      - *aws-sm
      - *private-npm
      - seek-jobs/gantry#v1.6.2:
          command: build
          file: gantry.build.yml
          region: <%- region %>
          values: .gantry/common.yml

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!${BUILDKITE_PIPELINE_DEFAULT_BRANCH}'

  - concurrency: 1
    concurrency_group: <%- teamName %>/deploy/gantry/{{matrix.environment}}
    label: '{{matrix.label}}'
    matrix:
      adjustments:
        - with:
            environment: <%- devGantryEnvironmentName %>
            label: 🤞 Deploy Dev
            values: dev
          agents:
            queue: <%- devBuildkiteQueueName %>
          key: deploy-dev
        - with:
            environment: <%- prodGantryEnvironmentName %>
            label: 🚀 Deploy Prod
            values: prod
          branches: ${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
          depends_on: deploy-dev
      setup: {}
    plugins:
      - seek-jobs/gantry#v1.6.2:
          command: apply
          environment: '{{matrix.environment}}'
          file: gantry.apply.yml
          region: <%- region %>
          values:
            - .gantry/common.yml
            - .gantry/{{matrix.values}}.yml
    retry:
      manual:
        # Only use this if you need to roll back a deployment ASAP.
        # Always follow up with a proper revert or fix in Git history.
        permit_on_passed: true
